export const PLAYER_SHORTCUTS: [string, string][] = [
  ["Space or K", "Play / pause (click the video too)"],
  ["F or double-click", "Full screen on / off"],
  ["Esc", "Leave full screen"],
  ["↑ / ↓ or mouse wheel", "Volume up / down"],
  ["M", "Mute"],
  ["← / →", "Skip back / forward (10 s, change in Settings)"],
  ["Shift + ← / →", "Skip 5 seconds"],
  ["Alt + ← / →", "Skip 10 seconds"],
  ["Ctrl + ← / →", "Skip 1 minute"],
  ["[ / ]", "Slower / faster (0.25x to 8x)"],
  ["Backspace", "Normal speed (1x)"],
  ["0 – 9", "Jump to 0% – 90%"],
  ["Home / End", "Jump to start / end"],
  [", / .", "One frame back / forward (when paused)"],
  ["C or S", "Subtitles: next track / off"],
  ["Z / X", "Subtitles earlier / later (0.1 s)"],
  ["Shift + ↑ / ↓", "Bigger / smaller subtitles"],
  ["A", "Next audio track"],
  ["N / P", "Next / previous episode"],
  ["E", "Episode list"],
  ["W", "Picture: Fit / Fill / Stretch"],
  ["T", "Keep window on top"],
  ["Shift + M", "Mini player"],
  ["I", "Video information"],
  ["Ctrl + S", "Save a screenshot"],
  ["?", "Show these shortcuts"],
];

export const APP_SHORTCUTS: [string, string][] = [
  ["/ or Ctrl + F", "Go to Search"],
  ["Arrow keys", "Move between posters"],
  ["Enter", "Open the selected title"],
  ["Backspace", "Go back"],
  ["Right-click a poster", "Quick actions"],
  ["Ctrl + + / Ctrl + −", "Make everything bigger / smaller"],
  ["Ctrl + 0", "Normal size"],
];
